format = "$directory$git_branch$git_status$python$cmd_duration$time$character"
add_newline = false

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[directory]
truncation_length = 3
style = "bold blue"

[git_branch]
symbol = " "
style = "bold purple"

[git_status]
style = "yellow"
format = "([$all_status$ahead_behind]($style) )"
ahead = "⇡ ${count} "
behind = "⇣ ${count} "
diverged = "⇕ ⇡${ahead_count}⇣${behind_count} "

[python]
format = "[( $virtualenv)](bright-green) "
detect_extensions = []
detect_files = []
detect_folders = []

[cmd_duration]
min_time = 200
format = "[(⏱ $duration)](bright-black) "

[time]
disabled = false
format = "[( $time)](bright-black) "
time_format = "%H:%M:%S"
