format = "$directory$git_branch$git_status$python$cmd_duration$time$character"
add_newline = false

[character]
success_symbol = "❯"
error_symbol = "❯"

[directory]
truncation_length = 3
style = "bold cyan"

[git_branch]
symbol = " "
style = "bold purple"

[git_status]
style = "purple"
format = "([$all_status$ahead_behind]($style) )"
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "

[python]
format = "[( $virtualenv)](yellow) "
detect_extensions = []
detect_files = []
detect_folders = []

[cmd_duration]
min_time = 200
format = "[(⏱ $duration)](bright-black) "

[time]
disabled = false
format = "[( $time)](bright-black) "
time_format = "%H:%M:%S"
