[general]
import = ["~/.config/alacritty/themes/themes/ashes_dark.toml"]
live_config_reload = true


[window]
dimensions = { columns = 200, lines = 50 }
position = { x = 0, y = 0 }
decorations = "Buttonless"
dynamic_padding = true
blur = true
opacity = 0.9
decorations_theme_variant = "Dark"
startup_mode = "SimpleFullscreen"

[font]
normal = { family = "JetBrainsMono Nerd Font Mono" }
size = 12

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true
