[general]
import = ["~/.config/alacritty/themes/themes/ashes_dark.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 200, lines = 50 }
position = { x = 0, y = 0 }
decorations = "Buttonless"
dynamic_padding = true
blur = true
opacity = 0.95
decorations_theme_variant = "Dark"
startup_mode = "Maximized"

[font]
normal = { family = "JetBrainsMono Nerd Font Mono" }
size = 12

# normal = { family = "MonaSpiceNe Nerd Font Mono" }
# normal = { family = "MonoLisa Nerd Font Mono" }

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true
